"""Add Grade to ToDo model

Revision ID: 2869498002b2
Revises: b7717ef974e5
Create Date: 2024-12-13 15:12:24.512039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2869498002b2'
down_revision = 'b7717ef974e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('q1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('q4', sa.Integer(), nullable=True))
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=False))
        batch_op.drop_column('q4')
        batch_op.drop_column('q3')
        batch_op.drop_column('q2')
        batch_op.drop_column('q1')

    # ### end Alembic commands ###
