"""Add Grade to ToDo model

Revision ID: e10a43bc3d96
Revises: d995ece8a1a0
Create Date: 2024-12-26 12:43:54.048000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10a43bc3d96'
down_revision = 'd995ece8a1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('light_mode', sa.Boolean(create_constraint=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('light_mode')

    # ### end Alembic commands ###
